import { createFileRoute, Link } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ClosingCta } from "@/components/cta";
import { Button } from "@/components/ui/button";
import { services } from "@/lib/site-data";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [{ title: "Marketing Services — Growthora" },{ name: "description", content: "Custom SEO, ads, websites, social media, apps, branding, content, email and performance marketing for local businesses." },{ property: "og:title", content: "Marketing Services — Growthora" },{ property: "og:description", content: "Focused marketing services built around your local business goals." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/services" }] }), component: ServicesPage });

function ServicesPage() { return <><PageHero eyebrow="Services" title="Focused marketing, shaped around your goals." body="Choose the capabilities you need, or let your free audit show where to start. Every plan is quoted for your business." /><section className="py-16 sm:py-24"><div className="container-shell grid gap-8 lg:grid-cols-2">{services.map((s,i) => <article id={s.slug} key={s.slug} className="scroll-mt-28 rounded-lg border border-border bg-card p-7 shadow-card sm:p-9"><div className="grid grid-cols-[auto_minmax(0,1fr)] gap-5"><div className="grid h-12 w-12 place-items-center rounded-lg bg-secondary/10 text-secondary"><s.icon /></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-accent">Service {String(i+1).padStart(2,"0")}</p><h2 className="mt-1 font-display text-2xl font-semibold text-primary">{s.title}</h2></div></div><p className="mt-6 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Best for:</strong> {s.forWhom}</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{s.deliverables.map(d => <li key={d} className="flex gap-2 text-sm text-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-secondary"/>{d}</li>)}</ul><Button asChild variant="navyOutline" className="mt-7"><Link to="/contact">Get a custom quote</Link></Button></article>)}</div></section><ClosingCta /></> }